openapi: 3.0.0
info:
  title: Floral Store API
  description: API for Floral Store Aggregation
  version: 0.0.1

paths:
  /ping: &path_ping
    get:
      description: Get service health
      responses:
        200:
          $ref: "#/components/responses/Ping"
  /health: *path_ping
  /v1/auth/token/user:
    get: &v1_auth_token_user_get
      description: Issue Auth Token
      parameters:
        - in: query
          name: email
          required: true
          schema:
            type: string
        - in: query
          name: password
          required: true
          schema:
            type: string
      responses:
        200:
          "$ref": "#/components/responses/AuthToken"
        400:
          "$ref": "#/components/responses/Error"
    post: &v1_auth_token_user_post
      description: Verify Auth Token
      parameters:
        - "$ref": "#/components/parameters/AuthToken"
      responses:
        200:
          $ref: "#/components/responses/AuthTokenValidation"
                  
        400:
          $ref: "#/components/responses/Error"
  /v1/auth/token/store:
    get: *v1_auth_token_user_get
    post: *v1_auth_token_user_post

  /v1/users:
    post:
      description: Register user
      requestBody:
        $ref: "#/components/requestBodies/CreateUser"
      responses:
        201:
          $ref: "#/components/responses/User"
  /v1/users/{id}:
    get:
      description: Get user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          $ref: "#/components/responses/User"
        404:
          $ref: "#/components/responses/Error"
          
  /v1/stores:
      post:
        description: Register store
        requestBody:
          $ref: "#/components/requestBodies/CreateStore"
        responses:
          201:
            $ref: "#/components/responses/Store"
      get:
        description: Get stores
        responses:
          201:
            $ref: "#/components/responses/Store"
          404:
            $ref: "#/components/responses/Error"
  /v1/stores/{id}:
      get:
        description: Get store
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: integer
              format: int32
        responses:
          201:
            $ref: "#/components/responses/Store"
          404:
            $ref: "#/components/responses/Error"
  /v1/products:
    get:
      description: Get Products
      parameters:
        - in: query
          name: sort_by
          description: sort attribute
          required: false
          schema:
            type: string
            default: id
            enum:
              - id
              - price
              - store_id
              - max_height
        - in: query
          name: sort_order
          description: sort attribute
          required: false
          schema:
            type: string
            default: asc
            enum:
              - asc
              - desc
        - in: query
          name: filter
          description: filter attribute
          required: false
          schema:
            type: object
            properties:
              filter.like_name:
                type: string
                nullable: true
              filter.store_id:
                type: integer
                format: int32
                nullable: true
              filter.category_id:
                type: integer
                format: int32
                nullable: true
              filter.min_height:
                type: integer
                format: int32
                nullable: true
              filter.max_height:
                type: integer
                format: int32
                nullable: true
              filter.min_price:
                type: integer
                format: int32
                nullable: true
              filter.max_price:
                type: integer
                format: int32
                nullable: true
      responses:
        200:
          $ref: "#/components/responses/Products"
    post:
      description: Add Product
      requestBody:
        $ref: "#/components/requestBodies/CreateProduct"
      responses:
        201:
          $ref: "#/components/responses/Product"
  /v1/products/{id}:
    get:
      description: Get Product
      parameters:
        - in: path
          name: id
          description: ID of the Product
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: Products
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Product" 
  /v1/categories:
    get:
      description: Get Categories
      responses:
        200:
          $ref: "#/components/responses/Categories"
    post:
      description: Add Category
      requestBody:
        $ref: "#/components/requestBodies/CreateCategory"
      responses:
        201:
          $ref: "#/components/responses/Category"
  /v1/categories/{id}:
    get:
      description: Get Category
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int32
      responses:
        200:
          $ref: "#/components/responses/Category"
  # /v1/cart:
  #   get:
  #     description: Get user's Cart
  #     parameters:
  #       - in: query
  #         name: id
  #         description: User's ID
  #         required: true
  #         schema:
  #           type: integer
  #           format: int32
  #     responses:
  #       200:
  #         description: User's cart
  #         content:
  #           application/json:
  #             schema:
  #               "$ref": "#/components/schemas/Cart"              
  # /v1/favorite:
  #   get:
  #     responses:
  #       200:
  #         description: Get favorite
  #         parameters:
  #           - in: query
  #             name: store_id
  #             description: ID of the Store
  #             required: false
  #             schema:
  #               type: integer
  #               format: int32
  # /v1/
  # /v1/
  # /v1/

components:
  responses:
    Ping:
      description: Healthcheck response
      x-go-name: PingResponse
      content:
        application/json:
          schema:
            type: object
            required:
              - ts
            properties:
              ts:
                type: integer
                format: int64
    Message:
      description: Information Response
      x-go-name: MessageResponse
      content:
        application/json:
          schema:
            required:
              - message
            type: object
            properties:
              message:
                type: string
    Error:
      description: General Error
      x-go-name: ErrorResponse
      content:
        application/json:
          schema:
            type: object
            required:
              - error
            properties:
              error:
                type: string
    AuthToken:
      description: Authentication Token
      x-go-name: AuthTokenResponse
      content:
        application/json:
          schema:
            type: object
            required:
              - token
            properties:
              token:
                type: string
    AuthTokenValidation:
      description: AuthToken validation result
      x-go-name: AuthTokenValidationResponse
      content:
        application/json:
          schema:
            type: object
            required:
              - valid
            properties:
              valid:
                type: boolean
    User:
      description: User
      x-go-name: UserResponse
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/User"
    Store:
      description: Store
      x-go-name: StoreResponse
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Store"
    Stores:
      description: Stores
      x-go-name: StoresResponse
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Store"
    Category:
      description: Category
      x-go-name: CategoryResponse
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Category"
    Categories:
      description: Categories
      x-go-name: CategoriesResponse
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Category"
    Product:
      description: Product
      x-go-name: ProductResponse
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Product"
    Products:
      description: Products
      x-go-name: ProductsResponse
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Product"
  requestBodies:
    CreateStore:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - name
              - password
              - email
              - phone_number
            properties:
              name:
                type: string
                minLength: 3
                maxLength: 100
              password:
                type: string
                minLength: 6
                maxLength: 100
              email:
                type: string
                minLength: 6
                maxLength: 100
              phone_number:
                type: string
                minLength: 8
                maxLength: 24
    CreateUser:
      required: true
      x-go-name: CreateUserRequestBody
      content:
        application/json:
          schema:
            type: object
            required:
              - first_name
              - last_name
              - email
              - password
              - phone_number
            properties:
              first_name:
                type: string
                minLength: 2
                maxLength: 64
              last_name:
                type: string
                minLength: 2
                maxLength: 64
              email:
                type: string
                minLength: 5
                maxLength: 256
              password:
                type: string
                minLength: 6
                maxLength: 128
              phone_number:
                type: string
                minLength: 8
                maxLength: 24
    CreateProduct:
      required: true
      x-go-name: CreateProductRequestBody
      content:
        application/json:
          schema:
            type: object
            required:
              - store_id
              - name
              - description
              - image_url
              - price
              - min_height
              - max_height
              - category_id
            properties:
              store_id:
                type: integer
                format: int32
              name:
                type: string
              description:
                type: string
              image_url:
                type: string
              price:
                type: integer
                format: int32
              min_height:
                type: integer
                format: int32
              max_height:
                type: integer
                format: int32
              category_id:
                type: integer
                format: int32
    CreateCategory:
      required: true
      x-go-name: CreateCategoryRequestBody
      content:
        application/json:
          schema:
            type: object
            required:
              - name
              - description
            properties:
              name:
                type: string
                minLength: 4
                maxLength: 128
              description:
                type: string
                minLength: 0
                maxLength: 2048
  parameters:
    AuthToken:
      in: header
      name: &X_AUTH_TOKEN X-Auth-Token
      description: Authentication/API Token
      required: true
      schema:
        type: string
  schemas:
    Store:
      type: object
      required:
        - id
        - name
        - email
        - phone_number
        - created
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        email:
          type: string
        phone_number:
          type: string
        created:
          type: integer
          format: int64
    User:
      type: object
      required:
        - id
        - first_name
        - last_name
        - email
        - phone_number
      properties:
        id:
          type: integer
          format: int32
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        phone_number:
          type: string
    ProductCategory:
      required:
        - id
        - name
        - description
        - created
        - modified
      type: object
      properties:
        id:
          type: integer
          format: int32
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        password:
          type: string
        phone_number:
          type: string
        created:
          type: number
          format: int64
    Product:
      required:
        - id
        - store_id
        - name
        - description
        - image_url
        - price
        - min_height
        - max_height
        - category
        - created
      type: object
      properties:
        id:
          type: integer
          format: int32
        store_id:
          type: integer
          format: int32
        name:
          type: string
        description:
          type: string
        image_url:
          type: string
        price:
          type: integer
          format: int32
        created:
          type: integer
          format: int64
        category:
          type: object
          required:
            - id
            - name
            - description
          properties:
            id:
              type: integer
              format: int32
            name:
              type: string
            description:
              type: string
        min_height:
          type: integer
          format: int32
        max_height:
          type: integer
          format: int32
    Category:
      required:
        - id
        - name
        - description
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          minLength: 4
          maxLength: 128
        description:
          type: string
          minLength: 0
          maxLength: 2048
    Favorite:
      required:
        # - user_id
        - product_id
      type: object
      properties:
        user_id:
          type: integer
          format: int32
        product_id:
          type: integer
          format: int32
    CartPosition: &cart_position
      required:
        - order_id
        - product_id
        - quantity
      type: object
      properties:
        order_id:
          type: integer
          format: int32
        product_id:
          type: integer
          format: int32
        quantity:
          type: integer
          format: int32
    Cart:
      type: array
      items:
        type: object
        properties:
          product:
            "$ref": "#/components/schemas/Product"
          quantity:
            type: integer
            format: int32
    OrderPosition: *cart_position
    Order:
      required:
        - id
        - status
        - user_id
        - created
        - status_modified
      type: object
      properties:
        id:
          type: integer
          format: int32
        status:
          type: string
          description: Order status
          enum:
            - created
            - in_progress
            - processed
            - delivery
            - canceled
            - completed
        user_id:
          type: integer
          format: int32
        created:
          type: integer
          format: int64
        status_modified:
          type: integer
          format: int64
    ProductReview:
      required:
        - id
        - user_id
        - product_id
        - rating
        - review_text
        - created
        - modifed
      type: object
      properties:
        id:
          type: integer
          format: int32
        user_id:
          type: integer
          format: int32
        product_id:
          type: integer
          format: int32
        rating:
          minimum: 1
          maximum: 100
          type: number
          format: integer
        review_text:
          type: string
        created:
          type: integer
          format: int64