CREATE SCHEMA IF NOT EXISTS "floral";

DROP TYPE IF EXISTS "floral"."order_status";
CREATE TYPE "floral"."order_status" AS ENUM (
  'created',
  'in_progress',
  'processed',
  'delivery',
  'canceled',
  'completed'
);

CREATE TABLE IF NOT EXISTS "floral"."store" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "password" varchar(500) NOT NULL,
  "email" varchar(50) UNIQUE NOT NULL,
  "phone_number" varchar(16) NOT NULL,
  "created" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "floral"."user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(100) NOT NULL,
  "last_name" varchar(100) NOT NULL,
  "email" varchar(50) UNIQUE NOT NULL,
  "password" varchar(500) NOT NULL,
  "phone_number" varchar(16) UNIQUE NOT NULL,
  "created" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "floral"."product_category" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(60) NOT NULL,
  "description" VARCHAR(150) DEFAULT '',
  "created" timestamp NOT NULL,
  "modified" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "floral"."product" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "store_id" integer NOT NULL,
  "name" varchar(100) NOT NULL,
  "description" varchar(1000) DEFAULT '',
  "image_url" varchar(300) NOT NULL,
  "price" integer NOT NULL,
  "created" timestamp NOT NULL,
  "modified" timestamp NOT NULL,
  "category" integer
);

CREATE TABLE IF NOT EXISTS "floral"."product_common_traits" (
  "product_id" integer PRIMARY KEY NOT NULL,
  "min_height" smallint,
  "max_height" smallint,
  "created" timestamp NOT NULL,
  "modified" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "floral"."user_favorite" (
  "user_id" integer NOT NULL,
  "product_id" integer NOT NULL,
  PRIMARY KEY ("user_id", "product_id")
);

CREATE TABLE IF NOT EXISTS "floral"."cart_position" (
  "user_id" integer NOT NULL,
  "product_id" integer NOT NULL,
  "quantity" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "floral"."order" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" floral.order_status,
  "user_id" integer NOT NULL,
  "created" timestamp NOT NULL,
  "status_modified" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "floral"."order_position" (
  "order_id" integer NOT NULL,
  "product_id" integer NOT NULL,
  "quantity" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "floral"."review" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "product_id" integer NOT NULL,
  "rating" float NOT NULL,
  "review_text" VARCHAR(2500),
  "created" timestamp NOT NULL,
  "modified" timestamp NOT NULL
);

CREATE INDEX IF NOT EXISTS "product_store_id_idx" ON "floral"."product" ("store_id");

CREATE INDEX IF NOT EXISTS "user_favorite_user_id_idx" ON "floral"."user_favorite" ("user_id");

CREATE INDEX IF NOT EXISTS "user_favorite_product_id_idx" ON "floral"."user_favorite" ("product_id");

CREATE INDEX IF NOT EXISTS "cart_position_user_id_idx" ON "floral"."cart_position" ("user_id");

CREATE INDEX IF NOT EXISTS "cart_position_product_id_idx" ON "floral"."cart_position" ("product_id");

CREATE UNIQUE INDEX IF NOT EXISTS "cart_position_user_id_product_id_key" ON "floral"."cart_position" ("user_id", "product_id");

CREATE INDEX IF NOT EXISTS "order_user_id" ON "floral"."order" ("user_id");

CREATE INDEX IF NOT EXISTS "order_position_order_id_idx" ON "floral"."order_position" ("order_id");

CREATE INDEX IF NOT EXISTS "order_position_product_id_idx" ON "floral"."order_position" ("product_id");

CREATE UNIQUE INDEX IF NOT EXISTS "order_position_product_id_order_id_key" ON "floral"."order_position" ("product_id", "order_id");

CREATE INDEX IF NOT EXISTS "review_user_id_idx" ON "floral"."review" ("user_id");

CREATE INDEX IF NOT EXISTS "review_product_id_idx" ON "floral"."review" ("product_id");

CREATE UNIQUE INDEX IF NOT EXISTS "review_user_id_product_id_key" ON "floral"."review" ("user_id", "product_id");

COMMENT ON COLUMN "floral"."product"."category" IS 'id of the product"s category';

COMMENT ON COLUMN "floral"."product_common_traits"."min_height" IS 'in cm';

COMMENT ON COLUMN "floral"."product_common_traits"."max_height" IS 'in cm';

-- TODO: make foreign key expessions idempotent
ALTER TABLE
  "floral"."product"
ADD
  FOREIGN KEY ("store_id") REFERENCES "floral"."store" ("id") ON DELETE NO ACTION ON UPDATE CASCADE;

ALTER TABLE
  "floral"."product"
ADD
  FOREIGN KEY ("category") REFERENCES "floral"."product_category" ("id") ON DELETE
SET
  NULL ON UPDATE CASCADE;

ALTER TABLE
  "floral"."product_common_traits"
ADD
  FOREIGN KEY ("product_id") REFERENCES "floral"."product" ("id") ON DELETE NO ACTION ON UPDATE CASCADE;

ALTER TABLE
  "floral"."user_favorite"
ADD
  FOREIGN KEY ("user_id") REFERENCES "floral"."user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE
  "floral"."user_favorite"
ADD
  FOREIGN KEY ("product_id") REFERENCES "floral"."product" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE
  "floral"."cart_position"
ADD
  FOREIGN KEY ("user_id") REFERENCES "floral"."user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE
  "floral"."cart_position"
ADD
  FOREIGN KEY ("product_id") REFERENCES "floral"."product" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE
  "floral"."order"
ADD
  FOREIGN KEY ("user_id") REFERENCES "floral"."user" ("id") ON DELETE NO ACTION;

ALTER TABLE
  "floral"."order_position"
ADD
  FOREIGN KEY ("order_id") REFERENCES "floral"."order" ("id") ON DELETE NO ACTION ON UPDATE CASCADE;

ALTER TABLE
  "floral"."order_position"
ADD
  FOREIGN KEY ("product_id") REFERENCES "floral"."product" ("id") ON DELETE NO ACTION ON UPDATE CASCADE;

ALTER TABLE
  "floral"."review"
ADD
  FOREIGN KEY ("user_id") REFERENCES "floral"."user" ("id") ON DELETE
SET
  NULL ON UPDATE CASCADE;

ALTER TABLE
  "floral"."review"
ADD
  FOREIGN KEY ("product_id") REFERENCES "floral"."product" ("id") ON DELETE NO ACTION ON UPDATE CASCADE;

----
ALTER TABLE
  "floral"."store"
ALTER COLUMN
  created
SET
  DEFAULT NOW();

ALTER TABLE
  "floral"."user"
ALTER COLUMN
  created
SET
  DEFAULT NOW();

ALTER TABLE
  "floral"."product_category"
ALTER COLUMN
  created
SET
  DEFAULT NOW();

ALTER TABLE
  "floral"."product_category"
ALTER COLUMN
  modified
SET
  DEFAULT NOW();

ALTER TABLE
  "floral"."product_common_traits"
ALTER COLUMN
  created
SET
  DEFAULT NOW();

ALTER TABLE
  "floral"."product_common_traits"
ALTER COLUMN
  modified
SET
  DEFAULT NOW();

ALTER TABLE
  "floral"."order"
ALTER COLUMN
  created
SET
  DEFAULT NOW();

ALTER TABLE
  "floral"."order"
ALTER COLUMN
  status_modified
SET
  DEFAULT NOW();

ALTER TABLE
  "floral"."review"
ALTER COLUMN
  created
SET
  DEFAULT NOW();

ALTER TABLE
  "floral"."review"
ALTER COLUMN
  modified
SET
  DEFAULT NOW();